import React from 'react';
import gStyle from '../General.module.css'
import styles from './Footer.module.css';

const Footer = () => {

    return (
        <div className={gStyle.margStruct}>
            <p className={styles.p}><a className={styles.link} href={'https://github.com/maxpavlovdp/activecharge'}>activecharge</a> is maintained by <a className={styles.link} href={'https://github.com/maxpavlovdp?tab=overview&from=2022-04-01&to=2022-04-20'}>maxpavlovdp</a>.</p>
            <p className={styles.pSecond}>This page was generated by <a className={styles.link} href={'https://pages.github.com/'}>GitHub Pages</a>.</p>
        </div>
    );
};

export default Footer;