ewelink:
  email: jasper.ua@gmail.com
  password: 12345678

deviceId: 1000d61c41

spring:
  datasource:
    url: jdbc:postgresql://178.18.251.90:5432/postgres
    username: km220
    password: 12345678
