# ewelink.region=eu
# ewelink.email=maxpavlov.dp@gmail.com
# ewelink.password=Nopassword1
# ewelink.countryCode=+380

# #main
# ewelink.appId = YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
# ewelink.appSecret = 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

# #backup
# #ewelink.appid = 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq';
# #ewelink.appSecret = '6Nz4n0xA8s8qdxQf2GqurZj2Fs55FUvM';

# # kiev boiler
# #deviceId=1001323420
# # stage (komariv dima diff)
# deviceId=10013bb124
# device.chargeTimeSecs=20






ewelink:
  region: eu
  email: jasper.ua@gmail.com
  password: 12345678
  countryCode: +380
  appId: YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
  appSecret: 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

device:
  chargeTimeSecs: 20
deviceId: 1000d61c41

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/220-km
    username: 220-km
    password: 12345678
