ewelink:
  region: eu
  email: maxpavlov.dp@gmail.com
  password: Nopassword1
  countryCode: "+380"
  appId: YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
  appSecret: 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

device:
  chargeTimeSecs: 30

station:
  scan-delay-ms: 3000
  scan-batch-size: 5
  scan-threads: 1
  scan-interval-ms: 3000

# docker
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/220-km
    username: 220-km
    password: 12345678

flyway:
  locations: "classpath:db/migration/pg"

server:
  forward-headers-strategy: framework

# #main
# ewelink.appId = YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
# ewelink.appSecret = 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

# #backup
# #ewelink.appid = 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq';
# #ewelink.appSecret = '6Nz4n0xA8s8qdxQf2GqurZj2Fs55FUvM';
