ewelink:
  email: jasper.ua@gmail.com
  password: 12345678

spring:
  datasource:
    url: jdbc:postgresql://178.18.251.90:5432/postgres
    username: km220
    password: 12345678

station:
  scan-delay-ms: 10000
  scan-batch-size: 5
  scan-threads: 1
  scan-interval-ms: 10000
