name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Set up JDK 17
#      uses: actions/setup-java@v2
#      with:
#        java-version: '17'
#        distribution: 'adopt'
#    - name: Build BE
#      run: ./gradlew clean build -x test
#    - name: Test
#      run: ./gradlew test -i
    - name: Build FE
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@octocat'
      - run: npm run build
    - name: Deploy to Dev. Copy jar
      uses: appleboy/scp-action@master
      with:
        host: 178.18.251.90
        username: root
        port: 22
        key: ${{ secrets.PRIVATE_KEY }}
        source: "build/libs/220-km.com-0.0.1-SNAPSHOT.jar, systemctl-run-be-dev.sh"
        target: "/220/"
    - name: Deploy to Dev. Run jar.
      uses: fifsky/ssh-action@master
      with:
        command: |
          systemctl restart run-220-be-dev.service
        host: 178.18.251.90
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
