# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build
      run: ./gradlew clean build -x test
    - name: Test
      run: ./gradlew test -i
    - name: Deploy to Dev copy
      run: scp build/libs/220-km.com-0.0.1-SNAPSHOT.jar root@178.18.251.90:/220/
     -name: Deploy to Dev run
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -la
        host: 178.18.251.90
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
    - name: Deploy to Stage
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /git/activecharge/
          git pull
          systemctl restart run-220-spring.service
          systemctl restart run-220.service
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
